abstract TriangulationInterface

abstract ConstrainedTriangulationInterface <: TriangulationInterface

immutable DelaunayTriangulation <: TriangulationInterface
  nodeSection::NodeTriangulationSection
  segmentSection::SegmentTriangulationSectionInterface
  elementSection::ElementTriangulationSectionInterface
  edgeSection::EdgeTriangulationSectionInterface
end

immutable ConstrainedDelaunayTriangulation <: ConstrainedTriangulationInterface
  nodeSection::NodeTriangulationSection
  segmentSection::SegmentTriangulationSectionInterface
  holeSection::HoleTriangulationSectionInterface
  regionSection::RegionTriangulationSectionInterface
  elementSection::ElementTriangulationSectionInterface
  edgeSection::EdgeTriangulationSectionInterface
end
